name: WIP-kun
author: Yusuke Otsuka <mjhd.devlion@gmail.com>
description: manage your PRs with WIP labels
inputs:
  token:
    description: github auth token
    required: true
  owner:
    description: github repository owner
    required: true
  repo:
    description: github repository name
    required: true
  targets:
   description: target to watch changes
   required: false
   default: 'label,title,commits'
  label:
    description: name of WIP Label
    required: false
    default: 'S-work-in-progress'
  title:
    description: WIP title prefix
    required: false
    default: 'WIP:'
  commits:
    description: WIP commit prefixes
    required: false
    default: 'fixup!,squash!,wip'
runs:
  using: docker
  image: Dockerfile
branding:
  icon: shield-off
  color: yellow
