// Code generated by MockGen. DO NOT EDIT.
// Source: ./github.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	github "github.com/mjhd-devlion/wip-kun/pkg/github"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// ListPullRequestsWithCommit mocks base method
func (m *MockClient) ListPullRequestsWithCommit(ctx context.Context, sha string) ([]github.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPullRequestsWithCommit", ctx, sha)
	ret0, _ := ret[0].([]github.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPullRequestsWithCommit indicates an expected call of ListPullRequestsWithCommit
func (mr *MockClientMockRecorder) ListPullRequestsWithCommit(ctx, sha interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPullRequestsWithCommit", reflect.TypeOf((*MockClient)(nil).ListPullRequestsWithCommit), ctx, sha)
}

// ListCommits mocks base method
func (m *MockClient) ListCommits(ctx context.Context, pullRequestNumber int) ([]github.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCommits", ctx, pullRequestNumber)
	ret0, _ := ret[0].([]github.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCommits indicates an expected call of ListCommits
func (mr *MockClientMockRecorder) ListCommits(ctx, pullRequestNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCommits", reflect.TypeOf((*MockClient)(nil).ListCommits), ctx, pullRequestNumber)
}
