name: CI

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Run a one-line script
      run: printenv
    - name: run
      run: cat $GITHUB_EVENT_PATH
