name: WIP君

on:
  pull_request:
    types: [labeled,unlabeled,opened,edited,reopened,synchronize]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Run a one-line script
      run: printenv
    - name: run
      run: cat $GITHUB_EVENT_PATH
    - name: WIP君
      uses: mjhd-devlion/wip-kun-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: mjhd-devlion
        repo: wip-kun-action
        label: 'work-in-progress'
        title: 'WIP:'
        commits: 'wip,fixup!'
