name: CI

on:
  push:
  pull_request:
    types: [assigned,unassigned、labeled,unlabeled,opened,edited,closed,reopened,synchronize,ready_for_review,locked,unlocked]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Run a one-line script
      run: printenv
    - name: run
      run: cat $GITHUB_EVENT_PATH
